<?php

/**
 * @file
 * Primary module hooks for Balidea Form module.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function balidea_form_theme($existing, $type, $theme, $path) {
  return [
    'balidea-form-result' => [
      'variables' => ['data' => []],
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function balidea_form_preprocess_html(&$vars) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof NodeInterface) {
    $vars['attributes']['class'][] = "balidea-type-" . $node->bundle();
  }

}

/**
 * Implements hook_page_attachments_alter().
 */
function balidea_form_page_attachments_alter(&$page) {
  $page['#attached']['drupalSettings']['site']['name'] = Drupal::config('system.site')->get('name');
}
